### ISSUE TITLE
Design LOGO "Morserera"!

### ISSUE THREAD

**Issue by 6MA-606** [RinShin-Dev/Morse-Code-Translator#4]
Let create our logo and theme!
- Cheese
- Morse code

![Image](https://github.com/user-attachments/assets/32e81e97-151c-4159-b1f9-691ecdd16bde)

**Comment by 6MA-606** [comment]
<table>
  <thead>
    <tr>
      <th>Logo Type</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Normal</td>
      <td><img src="https://github.com/user-attachments/assets/1ff9d5f1-900b-4ad8-86c7-f01dd1d87d8d" width="300px" /></td>
    </tr>
    <tr>
      <td>Mono</td>
      <td><img src="https://github.com/user-attachments/assets/bde3dc32-a835-4702-a4e0-28f33f12372f" width="300px" /></td>
    </tr>
  </tbody>
</table>

**Comment by 6MA-606** [comment]
What do you think? @AkaKitsune027

**Comment by AkaKitsune027** [comment]
> What do you think? @AkaKitsune027

I love your logo ! That's so lovely ! 💛💛✨

**Comment by 6MA-606** [comment]
> > What do you think? [@AkaKitsune027](https://github.com/AkaKitsune027)
> 
> I love your logo ! That's so lovely ! 💛💛✨

**Wooh!!! Let go!**
